version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tuser
      POSTGRES_PASSWORD: 11223344
      POSTGRES_DB: tdb
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ahmedtaaw@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 11223344
    ports:
      - "5050:80"

  backend:
    image: backend
    restart: always
    ports:
      - "8000:8000"

    